### ISSUE TITLE
Error Encountered During Training

### ISSUE THREAD

**Issue by Dongj909** [lizhh268/ShadowMaskFormer#1]
Dear author, hello. 
I encountered an error during training.The error message is as follows:

Traceback (most recent call last):
  File "train.py", line 146, in <module>
    avg_psnr = valid(val_loader, network)
  File "train.py", line 81, in valid
    output = network(source_img).clamp_(-1, 1)
  File "/home/GDICC/tan/anaconda3/envs/shadow/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/GDICC/tan/anaconda3/envs/shadow/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/GDICC/tan/anaconda3/envs/shadow/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x_mask'

I think that in the ShadowMaskFormer class, the forward method needs to receive two parameters, x and x_mask. However, when calling network(source_img), the x_mask parameter was not passed, resulting in this error.
Regarding line 81 in train.py: output = network(source_img).clamp_(-1, 1） how should it be modified? I would like to consult you on this."

**Comment by lizhh268** [comment]
You're right, you should change it to "output = network(source_img, mask_img).clamp_(-1, 1)"

**Comment by lwtgithublwt** [comment]
> You're right, you should change it to "output = network(source_img, mask_img).clamp_(-1, 1)"
@lizhh268 @Dongj909 我遇到了同样的问题，不知道您最后是如何解决的？仿照上面source_img格式，我自己添加了一个mask_img，但是在训练时每个epoch特别慢，不知道是否合理？非常感谢您的解答！

**Comment by Dongj909** [comment]
你好，不好意思。前面这个问题卡住后我去找其他实验先了。后续如果有继续我会回复你的




1273863023
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lizhh268/ShadowMaskFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月26日(星期三) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lizhh268/ShadowMaskFormer] Error Encountered During Training (Issue #1)





  
You're right, you should change it to "output = network(source_img, mask_img).clamp_(-1, 1)"
 @lizhh268 @Dongj909 我遇到了同样的问题，不知道您最后是如何解决的？仿照上面source_img格式，我自己添加了一个mask_img，但是在训练时每个epoch特别慢，不知道是否合理？
