### ISSUE TITLE
作者你好，能否提供有个参数计算的代码，非常感谢！

### ISSUE THREAD

**Issue by lwtgithublwt** [lizhh268/ShadowMaskFormer#2]
作者你好，能否提供有个参数计算的代码，非常感谢！

**Comment by prabhuiitdhn** [comment]
Hello. Do we have pretrained model available to test?
Thanks!

**Comment by lizhh268** [comment]
目前已有大量关于PSNR, SSIM以及RMSE的指标计算代码是开源的，如AAAI2023 ShadowFormer以及CVPR2023 ShadowDiffusion等工作
